### ISSUE TITLE
how to use drachtio-server with MicroSIP

### ISSUE THREAD

**Issue by scyuan** [drachtio/drachtio-server#152]
I startup drachtop-server by docker. and i install the MicoSIP.and then how to launch by MIcroSIP?https://www.microsip.org/downloads

**Comment by davehorton** [comment]
I'm sorry but your question does not have much to do with my software.

Generally speaking, you can use any sip client to integrate with drachtio.  You would need to configure the sip client to send INVITEs to the drachtio server (and REGISTERs as well if you like).  Of course, you would need to have written a drachtio application to handle these messages.

**Comment by scyuan** [comment]
> I'm sorry but your question does not have much to do with my software.
> 
> Generally speaking, you can use any sip client to integrate with drachtio. You would need to configure the sip client to send INVITEs to the drachtio server (and REGISTERs as well if you like). Of course, you would need to have written a drachtio application to handle these messages.

how to configure with my drachtio-server whihout account?
