### ISSUE TITLE
how to solve one directional video

### ISSUE THREAD

**Issue by scyuan** [drachtio/drachtio-server#155]
Hi dave!
I don't know if it is caused by NAT. my application flow is below:

browser(webRtcEndpooint)->server(webRtcEndpoint)->server(rtpEndpoint)->soft phone

browser can receive the video and audio sent by soft phone.but soft phone can't receive the video and audio from browser. The sdp negotiation is success from drachtio-server log.

**Comment by davehorton** [comment]
so I understand you have a drachtio app actings as a B2BUA, receiving a call from a browser and sending it to a softphone.

Questions:
1. What are you using as media proxy to convert srtp to rtp?
2. Is the softphone behind a NAT?  If so, how are you sending the INVITE there?  Is the softphone registering with the drachtio server?

**Comment by scyuan** [comment]
I use drachtio app actings as UAS. receiving invite from softphone. and send media from browser to softphone.

1. kurento-media-server.
2. soft phone is behind a NAT(symmetric).softphone doesn't register when connect sip server.It call by address and then application handle it.

**Comment by davehorton** [comment]
I would have to see the full drachtio log of the call, plus a pcap taken from the server running drachtio server and kurento to help further on this

**Comment by scyuan** [comment]
sorry for reply late.

below is drachtio server log (contract is yuansichao@yuansichao.com,others are spam).

[log20210302.txt](https://github.com/drachtio/drachtio-server/files/6067323/log20210302.txt)

here is server net log bt tupdump:
[target.cap.zip](https://github.com/drachtio/drachtio-server/files/6067608/target.cap.zip)

**Comment by scyuan** [comment]
If the information is not enough, please let me know

**Comment by scyuan** [comment]
this is captures when make unidirectional communication.
￼￼
![image](https://user-images.githubusercontent.com/20028204/109902856-f548cf80-7cd5-11eb-8bfa-68128a41041b.png)

when I change test environment from WAN to LAN.It can actually make bidirectional communication (same code). So I think maybe the network or SDP lead to the problem. I'm so confused.

**Comment by davehorton** [comment]
I am confused about the drachtio log you provided.  It only shows a single call -- an invite from a MicroSips client calling extension 110.  The call is connected to the Kurento media server.  We then see a re-invite from the same client.  That is all I see in the logs.  I do not see the second call you are talking about

**Comment by davehorton** [comment]
closed for lack of response.
