### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by IdlePhysicist** [drachtio/drachtio-server#157]
Hi Dave,

Quick question, is Drachtio Server capable of supporting IPv6 addresses? And if so is it capable of using both IPv4 & IPv6 simultaneously?

Thanks.

**Comment by davehorton** [comment]
Sorry, ipv6 is not currently supported

**Comment by IdlePhysicist** [comment]
Ok, thanks Dave.

I realise you are the sole dev on Drachtio, but do you have any timeline for IPv6?

**Comment by davehorton** [comment]
Not at the moment, mainly because until now no one has asked for it.  It would be helpful to understand the case / need for it in your environment, if you could share some details

**Comment by IdlePhysicist** [comment]
I will get that to you early next week via email. Thanks again.
