### ISSUE TITLE
Two outgoing INVITES on second reINVITE with B2BUA

### ISSUE THREAD

**Issue by simonljungberg** [drachtio/drachtio-server#158]
In a SIP-proxy using createB2BUA the first reINVITE is passed through as expected but when the second one arrives drachtio sends out two ones on the other leg.

Re-INVITE triggered with:
```
dlgOther.modify(
      req.body
      ,(err, response) => {
      if (err) {
        console.log('ERR', err)
      }
        res.send(200, {
          body: response
        })
    });
```

Works as expected:
[invite2.txt](https://github.com/drachtio/drachtio-server/files/6222807/invite2.txt)
Sends two INVITES on the other leg:
[invite3.txt](https://github.com/drachtio/drachtio-server/files/6222809/invite3.txt)

**Comment by davehorton** [comment]
This is coming from your application -- in other words your application is telling the drachtio server to send that additional invite.  You can see in the drachtio server log the messages from the application, because they are logged like this:
```
Client::read_handler read ...
```
So we need to troubleshoot the bug you have in your application.  If you would care to share the relevant part of that I could comment

**Comment by simonljungberg** [comment]
I realized that. One of these gets called twice. Or both gets called:
`
uas.on("modify", this._handleReInvite.bind(this, uas, uac));
uac.on("modify", this._handleReInvite.bind(this, uac, uas));
`

Triggering this:
`
_handleReInvite(dlg, dlgOther, req, res, signal) {
    dlgOther.modify(
      req.body
      ,(err, response) => {
      if (err) {
        console.log('ERR', err)
      }
        res.send(200, {
          body: response
        })
    });
  }

Fetching the drachtio-srf log to determine which it is.
`

**Comment by simonljungberg** [comment]
This is not an error in drachtio. A listener seems to be registered twice in the application.
Sorry to waste your time.

**Comment by davehorton** [comment]
no problem.  Glad you got to the bottom of it!
