### ISSUE TITLE
Seg Fault when handling mid-call REGISTER for call using tcp

### ISSUE THREAD

**Issue by rhondahollis** [drachtio/drachtio-server#169]
Hi Dave.

When you have a chance, can you please take a look at the logs that I've attached for a crash that is occurring during the handling of a REGISTER when the webrtcproxy is configured to use tcp for outgoing INVITE's? This only happens when the REGISTER comes in for a user that is on an active call. REGISTER's when there is no active call are succeeding.

I've tried forcing the REGISTER to use tcp, but that ends up hitting the seg fault even when there is no active call.

If there is any other info that may help, let me know. Thanks!

[coredump_drachtio.txt](https://github.com/drachtio/drachtio-server/files/6963992/coredump_drachtio.txt)
[crash_tcp_midcallRegister.txt](https://github.com/drachtio/drachtio-server/files/6963994/crash_tcp_midcallRegister.txt)
[register_ForceTcp.txt](https://github.com/drachtio/drachtio-server/files/6963995/register_ForceTcp.txt)

**Comment by davehorton** [comment]
what version are you running?  Also, are you running in docker or a host machine?

**Comment by rhondahollis** [comment]
I'm running v0.8.9-rc2-2-g0004a185c on a host machine (logs are from my Mac, but I originally encountered the issue in our linux environment).

**Comment by davehorton** [comment]
the stack trace wasnt all that helpful.  Could you try running drachtio server from within gdb (or lldb in mac) and when it crashes get the stack trace from there?

**Comment by davehorton** [comment]
@rhondahollis can you test the branch bugfix/issue-42 ?  I believe it should fix this issue.

Note: be sure to update submodules, as the fix is in a newer version of sofia-sip 
i.e. after fetching that branch do
```
git submodule update --init --recursive
```

**Comment by rhondahollis** [comment]
@davehorton This issue has been resolved with your bugfix/issue-42 branch. I am also only seeing two tcp connections created now for the SIP traffic. This looks like it is all working well, but if you can take a peek at the attached log to confirm the tcp connections are behaving the way you expect them to, that would be great. Thanks!

These are the two connections that I see now:
tcp        0      0 drachtio01-dev-s0:35197 208.73.144.98:sip       ESTABLISHED
tcp        0      0 drachtio01-dev-s03:sip  208.73.144.98:8309      ESTABLISHED

[drachtio_tcpFix.txt](https://github.com/drachtio/drachtio-server/files/7086736/drachtio_tcpFix.txt)

**Comment by davehorton** [comment]
Thanks, this has now been merged into main and tagged as v0.8.11-rc1.

That log looks clean to me, and as expected.  Thanks for finding and helping me fix a rather important bug!
