### ISSUE TITLE
Archived log files issue

### ISSUE THREAD

**Issue by spointer** [drachtio/drachtio-server#181]
Hello Dave,

I set the log file section of the drachtio-server as follows,
```
        <file>
            <name>/var/log/drachtio/drachtio.log</name>
            <archive>/var/log/drachtio/archive</archive>
            <size>20</size> 
            <maxSize>50</maxSize>
            <minSize>2000</minSize>
            <auto-flush>true</auto-flush>            
        </file>
```

but archived log files are not removed even though total size of archive directory is over 50MB.

The archive directory of my server is as follows:
drwxr-xr-x  12 test  staff       384 12  6 09:36 .
drwxr-xr-x   9 test  staff       288 12  6 09:36 ..
-rw-r--r--   1 test  staff  20971439 12  6 03:36 drachtio.log
-rw-r--r--   1 test  staff  20971517 12  6 04:47 drachtio.log00000
-rw-r--r--   1 test  staff  20971443 12  6 06:00 drachtio.log00001
-rw-r--r--   1 test  staff  20971449 12  6 07:11 drachtio.log00002
-rw-r--r--   1 test  staff  20971149 12  6 08:24 drachtio.log00003
-rw-r--r--   1 test  staff  20971520 12  6 09:36 drachtio.log00004
-rw-r--r--   1 test  staff  20971485 12  5 22:52 drachtio.log00006
-rw-r--r--   1 test  staff  19669551 12  5 23:59 drachtio.log00007
-rw-r--r--   1 test  staff  20971483 12  6 01:11 drachtio.log00008
-rw-r--r--   1 test  staff  20971237 12  6 02:23 drachtio.log00009

**Comment by spointer** [comment]
server version is v0.8.13-rc1

**Comment by spointer** [comment]
I found the "maxFiles" option of the file logging section from drachtio-server and set to 5 but had no luck, archived log files keep accumulating, any reason?

**Comment by davehorton** [comment]
I will look into this

**Comment by spointer** [comment]
Hello Dave,
Any update on this?

I tried linux logrotate as an alternative but had no luck.

/var/log/drachtio/drachtio.log {
    daily
    rotate 10
    size 500M
    compress
    missingok
    notifempty
    copytruncate
}

**Comment by davehorton** [comment]
Hope to look at this in the next release, once I get 0.8.13 out

**Comment by spointer** [comment]
Hello Dave,
Any updates on this?

I checked the archive directory and it keeps growing.
Here is my logging section.

        <file>
            <name>/var/log/drachtio/drachtio.log</name>
            <archive>/var/log/drachtio/archive</archive>
            <size>500</size> 
            <maxSize>5000</maxSize>
            <minSize>10000</minSize>
            <maxFiles>5</maxFiles>
            <auto-flush>true</auto-flush>            
        </file>

**Comment by davehorton** [comment]
can you remove the minSize param and see if it works properly?

**Comment by spointer** [comment]
When i removed all drachtio log files(including archive) and restarted drachtio-server, it seems like working well.
I modified logging section for testing purpose like this.
        <file>
            <name>/var/log/drachtio/drachtio.log</name>
            <archive>/var/log/drachtio/archive</archive>
            <size>2</size> 
            <maxSize>5</maxSize>
            
            <maxFiles>1</maxFiles>
            <auto-flush>true</auto-flush>            
        </file>   

I'm going to test more cases and let you know.

Thank you.

**Comment by spointer** [comment]
The log rotation and archiving options works well.
I could not guess that other options are ignored when minSize option exists.

Thanks anyway.

**Comment by davehorton** [comment]
so basically when minSize is provided it apparently overrules the other settings, is that it?

**Comment by spointer** [comment]
Yes, as you mentioned in docs, it seems archive directory is maintained until minSize is reached because i saw archived logs were never removed when minSize exists.
