### ISSUE TITLE
Unable to connect using Websocket

### ISSUE THREAD

**Issue by GigaDroid** [drachtio/drachtio-server#186]
I'm starting the docker image like this:` docker run --name drachtio -p 5060:5060 -p 9022:9022 drachtio/drachtio-server drachtio --contact "sip:*;transport=tcp,udp,ws"`
Then I'm starting my Node.js app, which is basically the starter app mentioned in the docs. Here I'm getting the following output: connected to a drachtio server listening on: `udp/127.0.0.1:5060,tcp/127.0.0.1:5060,ws/172.17.0.2:5060,ws/127.0.0.1:5060,tcp/172.17.0.2:5060,udp/172.17.0.2:5060`
So far so good. Now I'm trying to connect by creating a websocket using Javascript.
`new WebSocket("ws://127.0.0.1:5060", "sip");`
See documentation here: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket
However I'm receiving `WebSocket connection to 'ws://172.17.0.2:5060/' failed` with no further information.

**Comment by davehorton** [comment]
please show the drachtio logs

Likely the issue is you can not listen for tcp and ws on the same port

**Comment by davehorton** [comment]
I don't know about this
```
new WebSocket("ws://127.0.0.1:5060", "sip");
```
It is saying that you want to establish a websocket connection with a subprotocol of sip.  The typical case of using sip over websockets is to use either the jssip or sip.js frameworks.

Having said that, can you get a wireshark trace showing the attempted connection?  Also, turn sofia-loglevel to 9 on the drachtio server

**Comment by GigaDroid** [comment]
Yes I'm indeed trying to use jssip but it fails when calling new WebSocket() inside of the library. Also tried sip.js but it fails at the same part. Logs with loglevel 9 and Wireshark trace attached.
[drachtio.log](https://github.com/drachtio/drachtio-server/files/7835829/drachtio.log)
[capture.zip](https://github.com/drachtio/drachtio-server/files/7835837/capture.zip)

**Comment by spointer** [comment]
I use sip.js and it works well with wss
