### ISSUE TITLE
Can't find dialog for dialog id 

### ISSUE THREAD

**Issue by spointer** [drachtio/drachtio-server#190]
Hello Dave,

When i call dialog.destroy from drachtio-srf side, the remote peer sends 407 proxy authentication required response and the call is not hung up.
So, I called dialog.request with method BYE including auth object instead of dialog.destroy but  drachtio-server replies error to srf side.

I could see "Can't find dialog for dialog id xxxxx" log from the drachtio-server and it seems this is because the drachtio-server destroys SipDialog even though it received 401/407 response from remote peer.

Do you have any suggestions?
Thank you.

**Comment by davehorton** [comment]
I have never heard of a SIP server rejecting a BYE request on a dialog of a 407.  Can you send the drachtio log file showing that?  What product is doing this?

**Comment by spointer** [comment]
It's Avaya SM-8.1.2.1

I will send the logs to your email.

**Comment by spointer** [comment]
I sent logs to your email.
Thank you.

**Comment by davehorton** [comment]
Is there any chance of getting documention or information from Avaya on this practice of challenging requests within a dialog, when the initial INVITE was presumably already challenged?  I'd be happy to support this if I can be shown an RFC that indicates this is allowed...

**Comment by spointer** [comment]
Could you please check this link?

https://stackoverflow.com/questions/14066587/sip-getting-407-response-for-bye-request


If a proxy challenges a request generated by the UAC, the UAC has to resubmit the request with credentials.

**Comment by davehorton** [comment]
how is the dialog initially being established?  you are calling srf.createB2BUA, or srf.createUAC ?

**Comment by davehorton** [comment]
Looking into fixing this, but calling dialog.request with method BYE should have worked.  I cant see the error from the pics you provided but if you care to share a proper log file I will have a look

**Comment by spointer** [comment]
Hello Dave,
I sent the log to your email.

It seems there are two errors raised sequentially on the drachtio-srf side.

First, drachtio-agent of drachtio-srf side receives 407 message and calls authenticate function of DigestClient class but drachtio-server sends an error message including "Unable to find dialog for dialog id provided". It seems this is raised because the drachtio-server already destructed the SipDialog.

Second, "on of undefined" error is raised because client.authenticate function of drachtio-agent.js emits the callback without no req obj.

Thank you.

**Comment by davehorton** [comment]
can you test with drachtio-srf@4.4.62 and the latest main branch for drachtio-server?

**Comment by spointer** [comment]
Hello Dave,
I applied drachtio-server(v0.8.14-2-gc3e117408) and tested.
It's working well.

BTW, i forgot to apply drachtio-srf@4.4.62 and could not check.
I'll apply the latest drachtio-srf as soon as possible and let you know.

Thank you.

**Comment by davehorton** [comment]
great let me know and then please close this issue if all is ok

**Comment by spointer** [comment]
Hello Dave,
Sorry for late and it works.
