### ISSUE TITLE
drachtio removes dialog when got NOTIFY SIP message

### ISSUE THREAD

**Issue by spointer** [drachtio/drachtio-server#200]
Hello Dave,
I found drachtio removes dialog when NOTIFY message received.

The dialog flows are like this,

1. drachtio sends REFER message
2. remote SIP server sends NOTIFY(with SIP/2.0 180 Ringing body)
3. remote SIP server sends NOTIFY(with SIP 200 OK body)
4. drachtio removes dialog
5. remote SIP server sends BYE
6. drachtio sends 481 error response
7. drachtio-srf side can not get dialog destroy event

I think this happens inside ClientController::route_request_inside_dialog function.
Is it right?

Thank you.

**Comment by davehorton** [comment]
Yes I think you have identified a bug.  I will look into it.  Many thanks

**Comment by davehorton** [comment]
what release of drachtio-server are you running?

**Comment by davehorton** [comment]
fixed in v0.8.17-rc4

**Comment by spointer** [comment]
Sorry for late, i am running v0.8.16-2-ge1a7f66df.
I will test your fixed version and let you know.

Thank you.

**Comment by spointer** [comment]
I tested today and it works well.

Thank you.
