### ISSUE TITLE
SIP Register duplicated

### ISSUE THREAD

**Issue by spointer** [drachtio/drachtio-server#205]
Hi Dave,
When set --external-ip to drachtio-server and trying registration in drachtio-srf side, drachtio-server sends two Register SIP messages to the remote server. one with NAT'ed IP(K8s Pod IP) and the other with external IP.

Could you look into this?

Thank you.

**Comment by davehorton** [comment]
logs please

**Comment by spointer** [comment]
So sorry, I had misunderstood the sip messages from wireshark.
