### ISSUE TITLE
Incorrect link in the README?

### ISSUE THREAD

**Issue by lminiero** [drachtio/drachtio-server#219]
Hi,

I think the README may have an incorrect line in the "Building from source" section. The git clone line refers to a `git://github.com/davehorton/drachtio-server.git` that didn't go anywhere for me (the command was stuck and didn't proceed), and worked when I switched to `https`. I believe the problem may be that for git based links you should do something like `git@github.com:davehorton/drachtio-server.git` instead, but I'm not sure if the link format you used is supposed to work as well.

**Comment by davehorton** [comment]
Ah, thank you!  Will look into and fix
