### ISSUE TITLE
Drachtio rejecting INVITEs of forked calls due to duplicate Call-ID header

### ISSUE THREAD

**Issue by DBoag** [drachtio/drachtio-server#261]
Hi,

We have a voice infrastructure with multiple Drachtio servers for load balancing and redundancy. An "phone line" might have multiple registrations, for instance they might have a webphone open on 2 PCs and an iOS app and Android app all registered with the same phone number. Inbound calls are forked by a Kamailio server based on registration information we hold in a Redis database, and this might mean that multiple (forked) INVITES might be sent to the same Drachtio server, and this is causing us problems due to the "duplicate" Call-Id header.

When forking, Kamailio will add Via headers for each branch, but the Call-Id remains the same in each INVITE. For example, here are the Via headers from multiple INVITES that Kamailio sends to (the same) Drachtio where we see the top header has an incrementing number:

First INVITE:
```
Via: SIP/2.0/UDP 10.155.248.52;branch=z9hG4bKfeac.cc51c423b1e63de15186beb341ce3654.1
Via: SIP/2.0/UDP 197.155.251.199;branch=z9hG4bKfeac.8c92a7a2eff39a21a3c29679df7620c2.0
Via: SIP/2.0/UDP 197.155.251.202:5070;received=197.155.251.202;branch=z9hG4bK34e83bee;rport=5070
```

Second INVITE:
```
Via: SIP/2.0/UDP 10.155.248.52;branch=z9hG4bKfeac.cc51c423b1e63de15186beb341ce3654.2
Via: SIP/2.0/UDP 197.155.251.199;branch=z9hG4bKfeac.8c92a7a2eff39a21a3c29679df7620c2.0
Via: SIP/2.0/UDP 197.155.251.202:5070;received=197.155.251.202;branch=z9hG4bK34e83bee;rport=5070
```

But in the Drachtio logs, when it receives the second INVITE it thinks it's a retransmission:

`2023-03-01 12:28:04.440444 discarding retransmitted request: 573d4c1d266edc525880bff4622623a7@[sip4.telviva.com](http://sip4.telviva.com/)`

This log line generated by this drachtio-server code (drachtio-server/src/controller.cpp):

```
                        if( m_pPendingRequestController->isRetransmission( sip ) ||
                            m_pProxyController->isRetransmission( sip ) ) {
                       
                            DR_LOG(log_info) << "discarding retransmitted request: " << sip->sip_call_id->i_id  ;
                            int ret = sip_method_invite == sip->sip_request->rq_method ? 100 : -1 ;
                            nta_msg_discard(m_nta, msg) ;  
                            return ret ;
                        }
```

Which in turns is using this check (drachtio-server/src/sip-proxy-controller.cpp):

```
    bool ProxyCore::ServerTransaction::isRetransmission(sip_t* sip) {
        return sip->sip_request->rq_method == sip_object( m_msg )->sip_request->rq_method ; //NB: we already know that the Call-Id matches
    }
```

From what I understand of this section of RFC 3261, I believe that Drachtio should be accepting these forked calls despite the duplicate Call-ID:

```
The branch parameter of the Via header field value is now
      mandatory for all elements to use.  It now plays the role of a
      unique transaction identifier.  This avoids the complex and bug-
      laden transaction identification rules from RFC 2543.  A magic
      cookie is used in the parameter value to determine if the previous
      hop has made the parameter globally unique, and comparison falls
      back to the old rules when it is not present.  Thus,
      interoperability is assured.
```

We previously did the call forking in Drachtio using the `simring` functionality in drachtio/drachtio-fn-b2b-sugar, but we'd like to move away from requiring a single Drachtio handle all call branches if possible.

Am I doing something wrong with our Drachtio configuration, or is this happening by design? 

Note that there are additional (custom) SIP headers not mentioned here that we pass from Kamailio that contain other information, such as Device URI, so that Drachtio can contact the correct endpoint.

**Comment by DBoag** [comment]
We resolved this problem by updating the `makeUniqueSipTransactionIdentifier` function in `/src/drachtio.cpp`. The following patch considers the branch when generating a unique identifier:

```
diff --git a/src/drachtio.cpp b/src/drachtio.cpp
index 68216aeb3..759e9b127 100644
--- a/src/drachtio.cpp
+++ b/src/drachtio.cpp
@@ -208,6 +208,11 @@ namespace drachtio {
           sip->sip_cseq->cs_method_name) ;
         str.append("|") ;
         str.append( boost::lexical_cast<std::string>(sip->sip_cseq->cs_seq) ) ;
+        if (sip->sip_via && sip->sip_via->v_branch) {
+            str.append("|") ;
+            str.append(sip->sip_via->v_branch) ;
+        }
+        DR_LOG(log_error) << "made a UniqueSipTransactionIdentifier: " << str;
     }
```

**Comment by davehorton** [comment]
FYI the fix above breaks the proxy scenario.  I committed what I believe is a proper fix [here](https://github.com/drachtio/drachtio-server/pull/282)
