### ISSUE TITLE
wss to support ping pong for webrtc 

### ISSUE THREAD

**Issue by vdharashive** [drachtio/drachtio-server#366]
for wss connection drachtio wss server to support pong message for ping. this help to monitor the client connection stability 

Using audiocodes sdk this is reproducible 

{0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, disconnectFile: {…}, outgoingFile: {…}, incomingFile: {…}, incomingRingFile: {…}, waitingFile: {…}, …}
main.337ed334.chunk.js:2 AgentAssistServiceAdapterSocketIO: socket error event: xhr poll error
main.337ed334.chunk.js:2 AgentAssistManager: connection status event: {"connectionStatus":{"connectionState":"disconnected","lastError":{"message":"xhr poll error"}}}
main.337ed334.chunk.js:2 AgentAssistAsyncTask - connect: completed
main.337ed334.chunk.js:2 CallUIManager: autoplay check: closing auto play notification, attempting to enable auto play if necessary
3main.337ed334.chunk.js:2 Autoplay policy -> sound enabled
main.337ed334.chunk.js:2 15:29:46.116 AC: keep-alive: Server does not support CRLF pong.
main.337ed334.chunk.js:2 15:29:51.568 send()
main.337ed334.chunk.js:2 15:29:51.572 sending message:REGISTER sip:sbc2-XXXX-np.XXX.ai SIP/2.0
Via: SIP/2.0/WSS 62f5odexjeyc.invalid;branch=z9hG4bK3438536
Max-Forwards: 69
To: <sip:support@sbc2-XXXX-np.XXX.ai>
From: "support" <sip:support@sbc2-XXXX-np.XXX.ai>;tag=ot6q8hirg8
Call-ID: vp66shq3n0vv9a5i7ipevk
CSeq: 3 REGISTER
Contact: <sip:support@62f5odexjeyc.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:d9a075c8-d4e0-4a21-97c1-29fe0c8eb52d>";expires=30
Expires: 30
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY,SUBSCRIBE
Supported: path,gruu,outbound
User-Agent: AC WebRTC Web Client v 2.4.7 SDK v 1.18.0 Chrome/126
Content-Length: 0

**Comment by davehorton** [comment]
drachtio currently supports tcp keepalive, it seems like that should be sufficient?  If not please provide details on why not.

**Comment by vdharashive** [comment]
@davehorton we are using Audiocodes webrtc sdk , which keeps sending ping pong to server , to check connection exists any rest in connection its not able to detect and reestablished connection,  this is causing calls to fail two wards webrtc

**Comment by davehorton** [comment]
so you are saying the requirement is to respond to a ws ping message?

**Comment by vdharashive** [comment]
@davehorton audiocodes doc

https://techdocs.audiocodes.com/session-border-controller-sbc/mediant-software-sbc/user-manual/version-740/content/um/SIP%20over%20WebSocket.htm

**Comment by vdharashive** [comment]
@davehorton yes 

To keep a WebSocket session alive, it is sometimes necessary to send regular messages to indicate that the channel is still being used. Some servers, browsers or proxies may close an idle connection. Ping-Pong WebSocket messages are designed to send non-application level traffic that prevents the channel from being prematurely closed. You can configure how often the device pings the WebSocket client, using the [WebSocketProtocolKeepAlivePeriod] parameter (see [Configuring WebRTC](https://techdocs.audiocodes.com/session-border-controller-sbc/mediant-software-sbc/user-manual/version-740/content/um/Configuring%20WebRTC.htm)). The device always replies to ping control messages with a pong message. The WebSocket protocol supports keep-alive using special frames, however it is used only on the server side; for the Web client, a special ping (CRLF) request is used which the device answers.

**Comment by davehorton** [comment]
@vdharashive can you supply me with a test client

**Comment by vdharashive** [comment]
@davehorton i have shared this in ticket

**Comment by vdharashive** [comment]
@davehorton can you look into this if this can help
https://sofia-sip.sourceforge.net/refdocs/tport/tport__tag_8h.html

Respond PING with PONG.

If true, respond with PONG to PING. Default value is 0 (false).

If set, the ping-pong protocol is used on TCP connections. If a ping (at least 4 whitespace characters) is received between messages, a pong (CR-LF) is sent in response.

Use with [tport_tcreate()](https://sofia-sip.sourceforge.net/refdocs/tport/tport_8h.html#a450d75c76aa219c54abf2f68d395774f), [tport_tbind()](https://sofia-sip.sourceforge.net/refdocs/tport/tport_8h.html#a3cf32dca62abd18069aa6189d7e16598), [tport_set_params()](https://sofia-sip.sourceforge.net/refdocs/tport/tport_8h.html#ab8e595125c2a893ed23962f4c8f6e680), [nua_create()](https://sofia-sip.sourceforge.net/refdocs/nua/nua_8h.html#a5143ffe880249d0570f428a20035641d), [nta_agent_create()](https://sofia-sip.sourceforge.net/refdocs/nta/nta_8h.html#a0a8c71bfc1f474c03f824ac5d1761d99), [nta_agent_add_tport()](https://sofia-sip.sourceforge.net/refdocs/nta/nta_8h.html#abad7e2b8b858395b9f9eb4f76daa59dc), nth_engine_create(), or initial [nth_site_create()](https://sofia-sip.sourceforge.net/refdocs/nth/nth_8h.html#aa66ebd53fc36c350cce3d614223f3788).

See also:
[TPTAG_PINGPONG()](https://sofia-sip.sourceforge.net/refdocs/tport/tport__tag_8h.html#a4689f65ef52cdf1c2aba5a091af7c24a), [TPTAG_KEEPALIVE()](https://sofia-sip.sourceforge.net/refdocs/tport/tport__tag_8h.html#a75d17ab83ee90adbe0654aea380c2c05), [TPTAG_TIMEOUT()](https://sofia-sip.sourceforge.net/refdocs/tport/tport__tag_8h.html#a2e2f9e19f0895de6b3bead094b75d949), [TPTAG_IDLE()](https://sofia-sip.sourceforge.net/refdocs/tport/tport__tag_8h.html#a404e041a3b3e6d5a3faf6f48f644f3d4)
Since:
New in [1.12.7](http://sofia-sip.sf.net/relnotes/relnotes-sofia-sip-1.12.7.txt).

**Comment by vdharashive** [comment]
@davehorton any thoughts on if this would be feasible to support

**Comment by davehorton** [comment]
will test this in the next couple of days.  Please provide sample webrtc client to test with

**Comment by vdharashive** [comment]
@davehorton I have shared the link in freshdesk

**Comment by davehorton** [comment]
This feature above in sofia is only available on tcp connections, not tls or wss.

**Comment by vdharashive** [comment]
@davehorton 

I could see the implementation for pong in ws 


https://github.com/freeswitch/sofia-sip/blob/0a50b8402fa5b6190a6c91c2e04dfe44a40de02c/libsofia-sip-ua/tport/tport_type_ws.c#L602

**Comment by davehorton** [comment]
That is a websocket ping, not the 2-byte CRLF your client is sending

**Comment by vdharashive** [comment]
Thanks @davehorton to implement this
