### ISSUE TITLE
Second INVITE for authentication not sent

### ISSUE THREAD

**Issue by AndreHeber** [drachtio/drachtio-server#386]
We authenticate during the INVITE process, which usually looks like that:
INVITE -> 407 Proxy Authentication Required (with nonce) -> ACK
INVITE (with nonce response) -> 200 OK -> ACK

But we experience that for a small amount of calls, the second INVITE is simply not sent and the process is stuck.
I've added the logs:
[sbc-sip-1-drachtio-no-auth.log](https://github.com/user-attachments/files/17495848/sbc-sip-1-drachtio-no-auth.log)

The `SipDialogController::processResponseOutsideDialog - retransmitted ACK for callid` log line is unusual, that isn't logged for successful calls. So I searched for other occurences of that line and every time that line is logged, something is odd with the call.

The responsible code:
```cpp
if (sip->sip_cseq->cs_method == sip_method_invite && m_timerDHandler.resendIfNeeded(orq)) {
    DR_LOG(log_info) << "SipDialogController::processResponseOutsideDialog - retransmitted ACK for callid: " << sip->sip_call_id->i_id  <<
        " for invite with orq: " << std::hex << (void *) orq;
    msg_destroy( msg ) ; 
    return 0;
}
```

And the `resendIfNeeded` function:
```cpp
// call this when we received a response to check it if is a retransmitted response
bool TimerDHandler::resendIfNeeded(nta_outgoing_t* invite) {
    mapInvite2Ack::const_iterator it = m_mapInvite2Ack.find(invite);
    if (it != m_mapInvite2Ack.end()) {
        outgoing_retransmit(it->second) ;
        return true;
    }
    else if (m_mapCallIdAndCSeq2Invite.size() > 0) {
        string callIdAndCSeq = combineCallIdAndCSeq(invite);
        if (m_mapCallIdAndCSeq2Invite.find(callIdAndCSeq) != m_mapCallIdAndCSeq2Invite.end()) {
            DR_LOG(log_error) << "TimerDHandler::resendIfNeeded - cannot retransmit ACK because app has not yet provided it " << nta_outgoing_call_id(invite);
            return true;
        }
    }
    return false;
}
```

And
```cpp
typedef std::unordered_map<nta_outgoing_t*, nta_outgoing_t*> mapInvite2Ack;
mapInvite2Ack 					m_mapInvite2Ack;
```

I suspect that there are cases, where the `orq`/`invite` is not erased from the `m_mapInvite2Ack` and the same memory address is used by a request for another call and then things go wrong.

**Comment by AndreHeber** [comment]
![image](https://github.com/user-attachments/assets/a4096b02-082d-42c9-ae3e-0193271f463e)
Maybe erasing the `org` from the `m_mapInvite2Ack` in the `SipDialogController::clearRIP` function?

**Comment by davehorton** [comment]
handling the 401/407 challenge is the responsibility of the client app, not the server

**Comment by davehorton** [comment]
Sorry for closing this too early @AndreHeber 

Yes, there appears to be an issue with this scenario:
- drachtio sends initial INVITE, gets 200 OK / ACK
- drachtio immediately sends re-INVITE, get 200 OK / ACK
- call ends within 30 seconds
- new call uses same orq memory address of reinvite from closed call

We will look into fix.  Meanwhile, can you verify which tag you experienced this on?

**Comment by AndreHeber** [comment]
```shell
$ drachtio -v
v0.8.26-rc1
```

**Comment by davehorton** [comment]
@AndreHeber this should be fixed in v0.8.27-rc1 (also available on Dockerhub as tag 0.8.27-rc1), could you apply and retest?

**Comment by Catharsis68** [comment]
@davehorton  are there any new on this topic?
The last thing was, we had deployed  drachtio-server 0.8.27-rc12 on the customer environment to fix these "silent calls" but afterwards the sbc was restarting constantly. 

I saw that there is a new [0.8.27-rc14](https://github.com/drachtio/drachtio-server/commits/v0.8.27-rc14/), but that is maily a rollback?

**Comment by davehorton** [comment]
No [0.8.27-rc14](https://github.com/drachtio/drachtio-server/commits/v0.8.27-rc14/) fixes those restarts.  However it does not solve the second invite problem.

I have a plan for that and should have a fix early next week

**Comment by AndreHeber** [comment]
We rolled out version [v0.8.27-rc17](https://github.com/drachtio/drachtio-server/commits/v0.8.27-rc17/), which fixes the issue.
Thank you!
