### ISSUE TITLE
HTTP "health check" url for Drachtio-server

### ISSUE THREAD

**Issue by jonastelzio** [drachtio/drachtio-server#94]
Hey hey!

When running an AWS Application Load Balancer in front of Drachtio-server, you configure a health check url that the load balancer requests regularly to check for the instance's availability.

Right now it works alright if you just specify the websocket interface, though it returns http 400, which is also sort of "fine" since we can configure ALB to accept 400 as being healthy.

I'm thinking though, that a more dedicated end point that responds HTTP 200 ok would be really nice. Not really urgently needed - what do you think?

**Comment by davehorton** [comment]
can you give me basic quick instructions on how to configure the AWS load balancer for this configuration?
